# Generated by Django 5.1.6 on 2025-03-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('max_questions', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_lan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.poemset'),
        ),
    ]
