# Generated by Django 5.1.6 on 2025-03-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poemset_alter_poem_poem_lan'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.CharField(default='asd', max_length=128),
            preserve_default=False,
        ),
    ]
